### ISSUE TITLE
改名字？

### ISSUE THREAD

**Issue by alanjqiu** [yangsr/omniauth-wechat-oauth2#2]
这个 repo 是为 open weixin 服务的，是否考虑把 repo 名字改为 omniauth-openweixin-oauth2 或者 omniauth-weixin-oauth2？

**Comment by yangsr** [comment]
Hi alan-qiu
     抱歉这么久才看到。开始的时候确实是想改一个名字的，后来没有考虑到合适的，也就暂时搁置了。再后来发布了，想改名字就远不如开发阶段那么方便了：)
