### ISSUE TITLE
微信公众平台和微信开放平台的OAuth同时接入

### ISSUE THREAD

**Issue by kevin-isky** [yangsr/omniauth-wechat-oauth2#5]
> 微信公众平台和微信开放平台的OAuth流程略有不同，请选择合适的gem使用。

我的理解是微信公众平台的OAuth适用于微信客户端访问web页面的情况，而开放平台提供的OAuth适用于非微信客户端的浏览器访问web页面的情况。所以想确认下是否可以针对不同的情况调用相应的OAuth，两个gem一起使用？

**Comment by yangsr** [comment]
Hi，

我没有尝试过两个gem一起使用，不过如果需要一起使用的话，可能还要关注下gem重名了是否会冲突。

不过正如你开头提到的，首先要考虑清楚的是，什么情况下需要使用微信公众平台的OAuth，什么情况下需要使用微信开放平台的OAuth。

这个问题可能需要你去ruby-china上发帖向在微信开发上经验丰富的同学咨询确认一下。
